baseURL = 'https://d25yyb6maftl28.cloudfront.net/' # TODO change
languageCode = 'en-us'
title = 'Note to Self'
theme = 'default'
uglyURLs = true
disableKinds = ["taxonomy", "term", "sitemap"]

[markup]
  [markup.highlight]
  style = 'github'

[deployment]
  [deployment.targets]
  name = "aws"
  URL = "s3://blog-lnsfn?region=us-east-1"
  # cloudFrontDistributionID = "E3ONZ7WE6FOB4H"
