baseURL = 'https://lae.nz'
languageCode = 'en-us'
title = 'Lae'
theme = 'default'
disableKinds = ["taxonomy", "term", "sitemap"]

[markup]
  [markup.highlight]
  style = 'github'

[outputs]
home = ["html", "rss"]
section = ["html"]
